### ISSUE TITLE
Pictures deleted after uninstalling app

### ISSUE THREAD

**Issue by rubennp91** [Mraulio/GBCamera-Android-Manager#21]
**Issue**: Pictures data is deleted from phone when app is uninstalled, if app is reinstalled, pictures data is lost
**Possible fix**: Keep data of pictures in phone storage even if app is deleted. Recognize the data if app is reinstalled
**Notes**: not entirely sure if this is a good practice within android app programming

**Comment by Mraulio** [comment]
The data is stored in the app database, so logically if you delete the app everything is wiped.
You can do a **JSON Backup** of your images and palettes, or download all images as png/txt.

**Comment by rubennp91** [comment]
I understand the logistics. Would you consider making the data more permanent so pictures can't be "accidentally" deleted forever?

The good thing about an app like GBCamera Android Manager is that it allows you to free space in your GB Camera to take more pictures. Since space in GB Camera is very limited, I get the feeling that users might import the data into the GBCamera Android Manager to then delete the pictures from the GB Camera. This makes, then the GBCamera Android Manager the only place where those pictures are stored. If no backup is created manually and the app is deleted for any reason, pictures are lost forever. I feel like it should not be that "easy" to delete them.

I know uninstalling an app is an intended action by the user. But in other cases like a picture gallery, you wouldn't lose the pictures from your camera if you deleted the "Photos" app.

**Comment by Mraulio** [comment]
If you use GBxCart to extract your images the SAV file is stored in your phone, so you don't lose your pics and can import them again.
If you use Arduino Printer Emulator you can save the txt output to a file manually when _printing_.
Other ways of importing images mean that you already have a file.
But I get your worries, I could try to do a database backup periodically or something like that.

**Comment by rubennp91** [comment]
I see, tinkering around now I found the SAV files from my previous imports.

I understand that in a way or another everything is saved on the phone. I don't think any changes are needed such that this should be an issue. I'll close it with this comment, thanks for your support.
