### ISSUE TITLE
Issue with Dark Mode Theme on phones.

### ISSUE THREAD

**Issue by zenaro147** [Mraulio/GBCamera-Android-Manager#7]
Hi! I found a bug on my phone (Galaxy S23) that uses dark theme/dark mode. It seems some colors didn't change properly, and the text turns to white, on a light background. Apparently this issue occurs only into the main screens.. on Menu, the colors seems right

Light Mode
<a href="https://postimg.cc/hzqYQk2Z" target="_blank"><img src="https://i.postimg.cc/hzqYQk2Z/Screenshot-20230607-121256-GBCamera-Manager.jpg" alt="Screenshot-20230607-121256-GBCamera-Manager"/></a>
<a href="https://postimg.cc/JHrdPbVb" target="_blank"><img src="https://i.postimg.cc/JHrdPbVb/Screenshot-20230607-121300-GBCamera-Manager.jpg" alt="Screenshot-20230607-121300-GBCamera-Manager"/></a>

Dark Mode
<a href="https://postimg.cc/PpzRWScX" target="_blank"><img src="https://i.postimg.cc/PpzRWScX/Screenshot-20230607-121314-GBCamera-Manager.jpg" alt="Screenshot-20230607-121314-GBCamera-Manager"/></a>
<a href="https://postimg.cc/0rP3kqMb" target="_blank"><img src="https://i.postimg.cc/0rP3kqMb/Screenshot-20230607-121318-GBCamera-Manager.jpg" alt="Screenshot-20230607-121318-GBCamera-Manager"/></a>

**Comment by Mraulio** [comment]
I'm closing the issue as this has been addressed at this [commit](https://github.com/Mraulio/GBCamera-Android-Manager/commit/e742cb7461f6f46b05828242f740a2faba319adb).
Thanks for opening the issue @zenaro147 and for the feedback on the Discord.
